import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import "./override.css";
import Header from "./header";
import Footer from "./footer";

const jetBrainsMono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "sakkke.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetBrainsMono.className} terminal`}>
        <div className="flex flex-col min-h-screen">
          <div className="container">
            <Header />
          </div>
          <div className="container flex flex-col grow">
            <div className="grow">{children}</div>
            <hr />
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
